//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace gamethebaiv2.Game
{


    public partial class Play
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// pnlEvent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEvent;

        /// <summary>
        /// eventTitle control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl eventTitle;

        /// <summary>
        /// eventDesc control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl eventDesc;

        /// <summary>
        /// btnChoice1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnChoice1;

        /// <summary>
        /// btnChoice2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnChoice2;

        /// <summary>
        /// btnChoice3 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnChoice3;

        /// <summary>
        /// rptFloors control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptFloors;

        /// <summary>
        /// pbHP control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pbHP;

        /// <summary>
        /// lblHP control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblHP;

        /// <summary>
        /// pbStress control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pbStress;

        /// <summary>
        /// lblStress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStress;

        /// <summary>
        /// pbExhaust control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pbExhaust;

        /// <summary>
        /// lblExhaust control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblExhaust;

        /// <summary>
        /// lblGold control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblGold;

        /// <summary>
        /// lblATK control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblATK;

        /// <summary>
        /// rptPaths control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptPaths;

        /// <summary>
        /// hfHistory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfHistory;

        /// <summary>
        /// hfPrevNode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfPrevNode;
    }
}